$:.unshift(File.dirname(__FILE__))
require 'dacs/errors'
require 'dacs/schema'
require 'dacs/permissive_schema'
require 'dacs/configured_value'
require 'dacs/environment_source'
require 'dacs/file_source'
require 'dacs/default_source'
require 'dacs/environment_source'
require 'dacs/app_config'
